### PR TITLE
[core] Handle invalid config on load

### LINKED ISSUE #409: Invalid config.cson results in "running" but has actually crashed on startup
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Filling out of the behalf of `Sinful712#2679` in the Discord. This is for posterity sake, the issue has already been resolved, but I would like to look into mitigating the cause.

With an invalidate config.cson, Pulsar shows as running within Task Manager, but no window ever loads.

```cson
"*":
  #Valid cson node
  "atom-path-intellisense":
    "manual-suggest": false
  #Invalid cson node, missing colon
  "one-dark-ui"
    hideDockButtons: true
```
Simply by missing a colon, the editor failed to load. This required the user to rename their `~/.pulsar` folder (as `--safe` didn't work) in order to validate if it was their settings, or something else.

### Pulsar version

1.102.2023022623

### Which OS does this happen on?

🪟 Windows

### OS details

11

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Edit config.cson
2. Add node with invalid scope (unsure if it's simply missing a colon while having secondary information underneath, or something else)
3. Attempt to launch Pulsar
4. Pulsar process should start, but no window ever loads

### Additional Information:

Pulsar running without Window
image

### PR DESCRIPTION
**Pull request by confused-Techie**
When Pulsar loads a user's config while the application is open there is proper error handling to warn of an invalid config. But it seems that if Pulsar is first starting up and finds an invalid config, it'll crash silently, while reporting that it is still running.

While I would've much preferred to not have to duplicate this error checking at all, unfortunately the other error checking is mostly special by being attached to an emitter, which during initial startup we don't have that same feature. So it seemed simple enough otherwise to implement. 

You can view the live changes error handling below:

https://github.com/pulsar-edit/pulsar/blob/5f3e40a2f5369f8cedad9ee42c747709241e34a1/src/config-file.js#L112-L117

But as for here, we will add just a small bit of error handling, which if it fails, will load the default config, just like the config file doesn't exist, as well as log a message to the terminal. We can from here let the live reloading take care of alerting the user.

---

Resolves #409

### CODE REVIEW

**Review by mauricioszabo — APPROVED** [review]
Even converted to async, great!

**Comment by confused-Techie** [comment]
Thanks a ton for the review @mauricioszabo!

File: src/main-process/start.js [hunk 1]
```diff
@@ -121,8 +121,14 @@ function getConfig() {
...
+      // Duplicated from `./src/config-file.js`.reload()
+      if (error) {
+        console.log(error.message);
+      } else {
+        config.resetUserSettings(data);
+      }
+    });
   }
 
   return config;
```
Comment (DeeDeeG) [inline src/main-process/start.js:134]: Sorry to look at this so late, but...

`config` is returned later. Is it _okay_ to do this stuff async?

I suppose without much deep knowledge about what this code does, the important question is "does `config.resetUserSettings(data)` modify the value of `config`, or is it done only for side-effects?

Is moving this to async possibly returning a different value of `config` than before, due to race conditions with async stuff "maybe finishing, maybe not finishing (probably not finishing)" before the `return config;` is done?
