### PR TITLE
Restore `right-clicked` class on a right-clicked tab

### LINKED ISSUE #349: Tabs package: right-clicking on a tab does not add a `right-clicked` class
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

[This pull request](https://github.com/atom/tabs/pull/531) made it so that right-clicking on a tab no longer adds a `right-clicked` class. The author notes that they regarded this behavior to be “unused,” but the [Zentabs](https://github.com/ArnaudRinquin/atom-zentabs) package relies on this behavior for its “Pin tab” and “Unpin tab” commands. It uses `.right-clicked` to identify which tab was right-clicked and trace it back to its associated editor pane.

I'm treating this as a bug because Pulsar allows a package to add commands to a tab's context menu, which means that those commands need some way to figure out which tab they were invoked from. There's no other obvious way that I can see, and if Pulsar restores the `.right-clicked` behavior, it will fix Zentabs (and other packages, probably) without their needing to push out an update.

I will be happy to contribute this fix myself if need be, but I'm opening this issue because I've not yet set up my local environment to do so.

### Pulsar version

1.101.0-beta

### Which OS does this happen on?

🍎 macOS

### OS details

11.7.2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open the inspector and inspect a tab element.
2. Right-click on that tab.
3. Observe that no classes are added to the `li` element that represents the tab.

### Additional Information:

_No response_

### PR DESCRIPTION
**Pull request by savetheclocktower**
Fixes #349.

### Identify the Bug

Until recently, when a tab was right-clicked, the `tabs` package marked it with a `right-clicked` class. As described in #349, [this PR](https://github.com/atom/tabs/pull/531) removed that functionality because of a belief that it was unused.

At least one popular package, [Zentabs](https://github.com/ArnaudRinquin/atom-zentabs), was broken by this change — when a user right-clicked a tab and selected **Pin Tab**, Zentabs used the `right-clicked` class to determine which tab the command was invoked against.

### Description of the Change

The code being restored is exactly equivalent to what was removed in the aforementioned PR.

### Alternate Designs

Because this was restoring code that used to be present, I didn’t think much about alternate approaches, but they can be explored once the regression is fixed.

### Possible Drawbacks

It occurs to me that, if you right-click on a tab and then exit the context menu, that tab will continue to bear the `right-clicked` class name until you right-click on a _different_ tab, but I think that’s OK.

### Verification Process

All existing tab specs pass. The new spec I wrote fails on `master` and passes on this PR branch.

By pinning this package in dev mode, I have ascertained that this fixes the Zentabs issue. I am once again able to pin a tab by right-clicking on it and selecting the **Pin Tab** option.

### Release Notes

Restores the ability of a package to know when a given tab was right-clicked on.

### CODE REVIEW

**Comment by Spiker985** [comment]
Interesting that the Atom team removed it because it seemed to be interfering with other things

Can you confirm that it doesn't interfere with the issue that the Atom team marked as fixed?

**Comment by savetheclocktower** [comment]
Not sure what you mean. If you mean the focus issue described in [atom/#531](https://github.com/atom/tabs/pull/531), I infer from context that the removal of `.right-clicked` didn't have anything to do with the underlying cause; this was just an opportunity to remove code that was seen as unnecessary. At any rate, all the specs added in that PR are still present, and are passing.

**Comment by savetheclocktower** [comment]
Also, now that I look more closely, [atom/tree-view#1205](https://github.com/atom/tree-view/pull/1205) is what we'd want to do long-term, assuming I'm reading it correctly. The invoked command would be able to consult `event.element` to know which tab was right-clicked on, which is much more elegant than looking for a class name.

We'd still want this PR in the short term, though, because it doesn't require affected packages to push an update just to fix the regression.

File: packages/tabs/spec/tabs-spec.js [hunk 1]
```diff
@@ -1274,6 +1274,16 @@ describe("TabBarView", () => {
...
+  describe("when the tab bar is right-clicked", () => {
+    it("adds the right-clicked class when right-clicked", () => {
+      triggerClickEvent(tabBar.tabAtIndex(0).element, {button: 2});
+      expect(tabBar.tabAtIndex(0).element.classList.contains('right-clicked')).toBe(true);
+      triggerClickEvent(tabBar.tabAtIndex(2).element, {button: 2});
+      expect(tabBar.tabAtIndex(2).element.classList.contains('right-clicked')).toBe(true);
+      expect(tabBar.tabAtIndex(0).element.classList.contains('right-clicked')).toBe(false);
+    });
+  });
+
```
Comment (DeeDeeG) [inline packages/tabs/spec/tabs-spec.js:1286]: Thanks for adding tests!

**Review by DeeDeeG — APPROVED** [review]
I'm not deeply familiar with how the right clicking logic is meant to work in the package ecosystem/around tabs, but I'll approve to indicate I have faith this is doing what it is intending to do.

Especially with the included tests passing in CI. (Test includes two positive "right-clicked" cases, and a negative "not right-clicked" (or more precisely a "not the most recently right-clicked tab" case), so the test scenario overall is somewhat unlikely to give false positives/false negatives.)

(Maybe @pulsar-edit/core have insight that this has only the intended effect and no unintended side effects? Would not mind a second opinion here from someone who's more familiar with this.)

**Review by mauricioszabo — APPROVED** [review]
I see no problem!

**Comment by DeeDeeG** [comment]
Thank you for the contribution, @savetheclocktower!

**Review by abirhasan132 — COMMENTED** [review]
#368
