### PR TITLE
[command-palette] Guard against failure to highlight a match

### LINKED ISSUE #911: "Uncaught TypeError: Cannot read property 'matchIndexes' of undefined" in command-palette
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Inputting certain terms into the command palette crashes it and makes it unusable.

### Pulsar version

1.113.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Reproduction steps:

1. Install atom-typescript
2. Activate the typescript package (Typescript: Activate)
3. Open the command palette
4. Start typing "typescript"

An error will be thrown with a stack trace like:

```
C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:139

TypeError: Cannot read property 'matchIndexes' of undefined
    at CommandPaletteView.highlightMatchesInElement (command-palette-view.js:139:13)
    at CommandPaletteView.createDescription (command-palette-view.js:209:10)
    at Object.elementForItem (command-palette-view.js:51:42)
    at C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\bookmarks\node_modules\atom-select-list\src\select-list-view.js:219:31
    at Array.map (<anonymous>)
    at SelectListView.renderItems (C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\bookmarks\node_modules\atom-select-list\src\select-list-view.js:215:35)
    at SelectListView.render (C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\bookmarks\node_modules\atom-select-list\src\select-list-view.js:199:12)
    at updateSync (C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\bookmarks\node_modules\etch\lib\component-helpers.js:107:34)
    at C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\bookmarks\node_modules\etch\lib\component-helpers.js:72:7
    at DefaultScheduler.performUpdates (C:\Users\jamai\AppData\Local\Programs\Pulsar\resources\app.asar\node_modules\etch\lib\default-scheduler.js:48:34)
```

The palette will no longer accept keystrokes, and once you close it, you won't be able to open it again without restarting Pulsar.

### Additional Information:

- I did not actually reproduce the problem in safe mode; however, I can try to reproduce the issue with a small toy package.
- Went through some of the debugging guide; issue seems to be linked to `atom-typescript`. Not sure if this is a Pulsar bug.
- `atom-typescript`'s activation is deferred; when I activate it and search for a prefix of "typescript" in the command palette, the error occurs

### PR DESCRIPTION
**Pull request by savetheclocktower**
Fixes #911.

### Identify the Bug

Not many people know this, but when a package author defines a command, they can [specify a _description_ for the command](https://github.com/pulsar-edit/pulsar/blob/master/src/command-registry.js#L84-L117) to elaborate on the command’s function. Hardly any packages use this feature — hell, built-in packages don’t use this feature! — but the `atom-typescript` authors knew it existed, and took advantage of it.

If a command has a description, you can type text that’s _only_ in the description and it’ll match. Hence when the command palette fuzzy-matches against user input, it tries to highlight both the command name _and_ the command description, if it exists.

This is fine. But since we’re now matching against either of _two_ strings, we have to be prepared for a match to fail in either case. #911 illustrates a case in which the user’s input fails to match against the description, then causes an exception because we didn’t imagine that matching could fail.

### Description of the Change

Guard against a match failure by falling back to an empty array instead of `undefined`.

### Alternate Designs

This regression was introduced when we moved to `atom.ui.fuzzyMatcher`, and it’s subtle enough that nobody noticed it until now. The root cause is probably that the `match` function it replaced from `fuzzaldrin` returned an empty array when there were no matches, whereas `atom.ui.fuzzyMatcher.match` seems to return `undefined`. (In this case, we’d need it to return not just an empty array, but an empty array with a `matchIndexes` property which is _also_ an empty array.)

That change is probably worth making, but for now we can just guard against a possible `undefined` value.

### Possible Drawbacks

None! But I’m going to hijack this section to talk about a different problem that I discovered when I went to add a test for this fix.

**`command-palette` uses a custom test runner, and I’m pretty sure its tests don’t get run as part of CI**. If they did, we would’ve caught this bug in the first place: four tests were already failing, including one that tested this exact scenario.

In one sense this is a devops problem to fix. But this could also be fixed by converting the `command-palette` tests to use the standard test runner. We can argue about that later!

### Verification Process

You can go through the steps enumerated in #911 and verify the fix that way.

In order to verify that fewer tests fail than before, you need to be able to run the tests. I was able to do so by

* opening a terminal to the `packages/command-palette` folder,
* running `npm install` to install the custom test runner, then
* running `pulsar --test test/command-palette-view.test.js`.

Before, four tests were failing; after, only one should fail. That failure is unrelated to this change and is based on an assumption that the fuzzy matcher would highlight the spaces in between words; I didn’t feel like taking the time to fix it.

### Release Notes

- Prevented an exception raised in the command palette in certain unusual filtering scenarios.

### CODE REVIEW

File: packages/command-palette/lib/command-palette-view.js [hunk 1]
```diff
@@ -135,8 +135,9 @@ export default class CommandPaletteView {
   highlightMatchesInElement (text, query, el) {
     const matches = atom.ui.fuzzyMatcher.match(text, query, {recordMatchIndexes: true})
     let matchedChars = []
-    let lastIndex = 0
-    matches.matchIndexes.forEach(matchIndex => {
+    let lastIndex = 0;
+    let matchIndexes = matches ? (matches.matchIndexes ?? []) : []
```
Comment (mauricioszabo) [inline packages/command-palette/lib/command-palette-view.js:139]:
```suggestion
    const matchIndexes = matches ? (matches.matchIndexes ?? []) : []
```

**Review by mauricioszabo — APPROVED** [review]
A single nitpick, left as a suggestion so you can apply directly, but still an easy approve!

File: packages/command-palette/lib/command-palette-view.js (hunk 1 above)
Comment (savetheclocktower) [reply packages/command-palette/lib/command-palette-view.js:139]: You _monster_
