### PR TITLE
[fix] Postinstall error with rm /usr/bin/pulsar

### LINKED ISSUE #215: Error occurs while installing from *.deb (installation does succeed).
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I downloaded the latest debian file and proceeded to install it with:

```bash
sudo dpkg -i ./pulsar_1.63.2022121205_amd64.deb
```

Which produced the following output (see rm error):

```
(Reading database ... 488852 files and directories currently installed.)
Preparing to unpack .../pulsar_1.63.2022121205_amd64.deb ...
Unpacking pulsar (1.63.2022121205) ...
Setting up pulsar (1.63.2022121205) ...
rm: cannot remove '/usr/bin/pulsar': No such file or directory
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

The installation does succeed, but it would probably be a good idea to fix up that error.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Pop!_OS 22.04 LTS

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Download the latest *.deb
2. Attempt to install with sudo dpkg -i 

### Additional Information:

_No response_

### PR DESCRIPTION
**Pull request by Spiker985**
Redirect stderr to /dev/null

Since this is a shell (sh) file and not a bash file, rather than doing an `if [[ -f "" ]]` condition, we can just throw away the error if it doesn't exist

A whole lot safer than using `-f/--force`

Should fix #215

### CODE REVIEW

**Review by DeeDeeG — COMMENTED** [review]
Seems legit.

Although if `/usr/bin/pulsar` already exists _and_ we get an error trying to `rm` it, maybe we _should_ print the error only in that case? So the "if exists then `rm`" way could give that benefit.

**Comment by Spiker985** [comment]
Man, that is quite annoying, renaming a branch which already has a PR, doesn't simply renamed the branch the PR is targeting - nah it deletes the whole thing

File: script/post-install.sh [hunk 1]
```diff
@@ -1,4 +1,12 @@
...
-rm /usr/bin/pulsar
-cp /opt/Pulsar/resources/pulsar.sh /usr/bin/pulsar
+FILESOURCE='/opt/Pulsar/resources/pulsar.sh'
+FILEDEST='/usr/bin/pulsar'
+
+if [ -f "$FILEDEST" ]
+then
+  rm "$FILEDEST"
+else
+  echo "File '$FILEDEST' not found (this is not an error)"
```
Comment (DeeDeeG) [inline script/post-install.sh:10]: Judging from past experience, I think we're still going to get asked about this even though it says it's not an error. :/ What can you do, people are curious.

So I think maybe change the message to be even friendlier/gentler, OR don't log if the file doesn't exist, since we don't really mind if this is a user's first install.

```suggestion
else
  echo "Info: file '$FILEDEST' not found (this is okay and not an error)"
```

Or just 

```suggestion
```

My two cents.

Comment (DeeDeeG) [reply script/post-install.sh:10]: Other than that, looks good to me!

**Review by confused-Techie — APPROVED** [review]
LGTM!

**Comment by DeeDeeG** [comment]
Thanks for this!
