### PR TITLE
Tree-sitter rolling fixes, 1.120 edition

### LINKED ISSUE #868: Tree sitter breaks code folding in certain cases
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

After installing the latest 1.13 version of Pulsar code folding in large javascript files "stops" at ~3500 lines.

On previous versions "ctrl-k ctrl-1" would fold the entire file at level 1 - it no longer does this. It folds the first 3500 or so and then does nothing after. You can still manually fold if you wish. 

When using the menu "Fold All" it does fold the entire file (at every level). 

toggling legacy tree-sitter in settings immediately fixes this.

### Pulsar version

1.13

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

22.04.3 LTS

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. Any large javascript file open in the editor pane.
2.Ctrl-k ctrl-1 
3.Scroll down to find the point it stops being folded.
4. Unfold all
5. Go to settings and toggle "legacy tree-sitter"
6. Return to edit pane
7. Ctrl-k ctrl-1 now folds the entire file.

### Additional Information:

I appreciate this may be an "edge" case with such a large file and currently I can enable legacy to work around.

### PR DESCRIPTION
**Pull request by savetheclocktower**
Fixes #868.

I feel lucky to be able to introduce this rolling PR so soon after the release. This first commit fixes a strange folding behavior that had been hanging around for about six months.

### CODE REVIEW

File: src/wasm-tree-sitter-grammar.js [hunk 1]
```diff
@@ -182,6 +182,7 @@ module.exports = class WASMTreeSitterGrammar {
     }).then(() => {
       this._queryFilesLoaded = true;
       this._loadQueryFilesPromise = null;
+      this.emitter.emit('did-load-query-files', this);
```
Comment (savetheclocktower) [inline src/wasm-tree-sitter-grammar.js:185]: I'll pre-emptively explain this so that it's here when someone (historically @DeeDeeG) looks over it.

A feature was requested that would require a new indentation query. I wanted to give the user a workaround that they could drop into their init file, but [found it surprisingly hard](https://github.com/pulsar-edit/pulsar/issues/877#issuecomment-2272552682) to pull it off.

The goal of the code in that comment is to take the content that's already in the indentation query, add an extra statement, then set that as the new indentation query for the grammar… _and_ have it apply to all editors without having to close and open a given file again.

But:

* You can't augment the existing indentation query until the grammar has initialized, or else you won't know what the current query is
* You can edit the query at that point, and set it as the new query for the grammar, but that doesn't automatically propagate to open files, since their instances of `WASMTreeSitterLanguageMode` fetched queries from the grammar already and will have to be told to reload them


Hence this fix:

* The new `onDidLoadQueryFiles` method tells you exactly when the queries have been loaded from disk
* The `setQueryForTest` method (originally meant only for specs, but I'll probably rename it at some point) will now fire an event that `WASMTreeSitterLanguageMode` automatically subscribes to

This is still a sloppy way to customize one's Tree-sitter queries, and there's further room for improvement in the future; but this improves the status quo.

File: src/wasm-tree-sitter-language-mode.js [hunk 2]
```diff
@@ -3310,6 +3346,27 @@ class LanguageLayer {
...
+  set indentsQuery(value) { this.queries.indentsQuery = value; }
+
+  get foldsQuery() { return this.queries.foldsQuery; }
+  set foldsQuery(value) { this.queries.foldsQuery = value; }
+
+  get tagsQuery() { return this.queries.tagsQuery; }
+  set tagsQuery(value) { this.queries.tagsQuery = value; }
+
+  get localsQuery() { return this.queries.localsQuery; }
+  set localsQuery(value) { this.queries.localsQuery = value; }
```
Comment (savetheclocktower) [inline src/wasm-tree-sitter-language-mode.js:3368]: This might need some explaining!

This was the result of an arbitrary choice I made about 16 months ago: to store the compiled queries as direct properties of each `LanguageLayer`.

* It feels untidy.
* It doesn't keep the queries themselves grouped together — as one might want to do if there's a reason to iterate through them.
* This is all still private API (as is all of `WASMTreeSitterLanguageMode`, but if that ever changes, I want this stuff to be more organized.

So now we're keeping them on a `queries` object. Some packages probably expect the queries to be present at their old locations, so I've added shims to support getting and setting the current list of queries from their legacy locations.

This is not a big deal. But the best time to have done this was ~16 months ago; the second best time is now.

File: packages/language-typescript/grammars/common/highlights.scm [hunk 3]
```diff
@@ -841,6 +841,9 @@
 "new" @keyword.operator.new._LANG_
 
 "=" @keyword.operator.assignment._LANG_
+
+["&" "|" "<<" ">>" ">>>" "~" "^"] @keyword.operator.bitwise.js
```
Comment (DeeDeeG) [inline packages/language-typescript/grammars/common/highlights.scm:845]: (re: af133b04f9ca6aed2ee68b03da4a7836391f92e5) Was going to ask if we should include bitwise assignment operators somehow, but I see they are already there later in the file...

I guess that's the part we did already. Heh.

Well, good to get these as well!

(For reference, if we want to check if we've got all of these, though I'm not _requesting_ that as a reviewer for the present PR. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators)

File: packages/language-typescript/grammars/common/indents.scm
Comment (DeeDeeG) [inline packages/language-typescript/grammars/common/indents.scm:1]: (re 11e2f75b0cefc091adc1391f1d0aaa02480717b5)

> handle a commonly encountered error state when the user is in the middle of typing a switch statement.

Sounds reasonable to me!

File: src/wasm-tree-sitter-language-mode.js (hunk 2 above)
Comment (DeeDeeG) [reply src/wasm-tree-sitter-language-mode.js:3368]: (re: 3b25873d1d040ebf7e27d535e35095917431264d)

I'm going to go with "I believe you". Sounds like the correct response.

Thank you for the notes!

File: src/wasm-tree-sitter-grammar.js (hunk 1 above)
Comment (DeeDeeG) [reply src/wasm-tree-sitter-grammar.js:185]: (re: 3b25873d1d040ebf7e27d535e35095917431264d)

Asking mostly because it's a bit arcane to me: Is this implementation risking being over-complicated?

If you envision some hypothetical world where a more green-field design were possible, is this how you'd want it to be done?

If not, is the limitation causing it to be done this way handed to us by Tree-sitter, or Atom/Pulsar stuff? Or is this sort of a convenient way to implement? And... any foreseen issues with this approach?

(Not sure why I'm asking all these questions, just trying to pick your brain a bit I guess. Good to know if you've considered it well before we merge it. Seems from the fact you chose to write it up preemptively that you probably have considered it. But anyway, bustin' chops today.)

**Review by confused-Techie — APPROVED** [review]
Took a look through this, and the changes seem straightforward enough I could mostly follow lol.

But tests are happy, the documentation within the code, and comments are verbose, precise, and perfectly explain to myself and others what's going on. All the code looks perfectly valid, and my understanding of changes within JS and TypeScript made total sense.

Plus there's an emphasis on cleaning up and organizing code, while being intentionally backwards compatible. So what's not to love? This all looks great to me, and I especially love "the second best time is now" comment

File: src/wasm-tree-sitter-language-mode.js
Comment (DeeDeeG) [inline src/wasm-tree-sitter-language-mode.js:1]: (Regarding ce6989e9f33f570f70af3c5cbfca0eb5c960b3db)

Seems legit! I believe the explanation, anyway! Code doesn't look too crazy, this is mostly adding specs, by diff line count. 👍 Specs are good to have!

Comment (DeeDeeG) [inline src/wasm-tree-sitter-language-mode.js:1]: (Regarding 358cb024a538483c466b4673822090746617884f)

Well explained, and I read the associated issue report. Seems like a good way of handling this, effectively the outer fold range starting on a line takes precedence seems to be the practical effect. Reasonable, IMO. 👍

File: packages/language-hyperlink/grammars/modern-tree-sitter-hyperlink.cson [hunk 4]
```diff
@@ -5,5 +5,6 @@ parser: 'tree-sitter-hyperlink'
 
 injectionRegex: 'hyperlink'
 treeSitter:
+  parserSource: 'github:savetheclocktower/tree-sitter-hyperlink#04c3a667ba432236578ac99bbacd0412f88d6fac'
```
Comment (DeeDeeG) [inline packages/language-hyperlink/grammars/modern-tree-sitter-hyperlink.cson:8]: 👍 (re: 80905582420a6ca1fc97f3508d02031643349d9c)

File: src/wasm-tree-sitter-language-mode.js [hunk 5]
```diff
@@ -3298,12 +3299,13 @@ class LanguageLayer {
...
       }
     }).then(() => {
-      if (atom.inDevMode()) {
-        // In dev mode, changes to query files should be applied in real time.
-        // This allows someone to save, e.g., `highlights.scm` and immediately
-        // see the impact of their change.
-        this.observeQueryFileChanges();
-      }
+      // This used to be called only in dev mode. But there are other use cases
+      // for dynamically reloading queries, so now we observer for changes in a
```
Comment (DeeDeeG) [inline src/wasm-tree-sitter-language-mode.js:3303]: **ACTIONABLE** (though not terribly important!)

Tiny typo "observer" --> "observe" ?

_Not a blocker._

File: spec/wasm-tree-sitter-language-mode-spec.js
Comment (DeeDeeG) [inline spec/wasm-tree-sitter-language-mode-spec.js:1]: (re 4388bced5f8a2c8b8db765d2b21f8d890d292e65)

Specs are appreciated! 👍

File: packages/symbol-provider-tree-sitter/lib/tree-sitter-provider.js [hunk 6]
```diff
@@ -1,6 +1,10 @@
 const CaptureOrganizer = require('./capture-organizer');
 const { Emitter } = require('atom');
 
+function layerHasTagsQuery(layer) {
+  return layer.queries?.tagsQuery ?? layer.tagsQuery;
+}
```
Comment (DeeDeeG) [inline packages/symbol-provider-tree-sitter/lib/tree-sitter-provider.js:6]: (re: 6846b9cef2fbc3816e2cfebcececa4e5d9ec85cf)

Had to brush up on optional chaining to see that this checks out. It does appear to check out as valid use of optional chaining.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Review by DeeDeeG — APPROVED** [review]
I'm kinda trusting that this works as intended, but I approve of the intent as described/stated, and I'm satisfied that I understand more or less what this is all intending to do.

So, to the extent I can offer meaningful review, and I do try, this gets a 👍 from me.

One typo found, look for the word **ACTIONABLE** to find it amongst my various review comments.

**Comment by DeeDeeG** [comment]
Two review-approves and both confused and I are comfortable merging this (context: prepping 1.20.0 at the moment), so, merging!

In terms of things to possibly circle back to later: there is that one typo I found, and a question I asked for clarification / "picking your brain" purposes, but neither are blockers!!

File: src/wasm-tree-sitter-grammar.js (hunk 1 above)
Comment (savetheclocktower) [reply src/wasm-tree-sitter-grammar.js:185]: > Asking mostly because it's a bit arcane to me: Is this implementation risking being over-complicated?

I don't think so? Some of the arcana about _how_ query files are loaded could maybe be simplified, but the basic way queries work — one query file for syntax highlighting, one for indentation, one for folding… — is broadly how Neovim does things, and probably other editors.

By comparison: if you wanted to customize how a TextMate grammar did…

* indentation: it was easy to override the existing value… but hard to augment it, since the existing value was a complex regular expression.
* folds: largely the same as indentations.
* syntax highlighting: no way to override without basically writing a whole new grammar.
* symbols: no way to override whatsoever.

I can't tell which aspect of the system you're asking about, but I can explain further if you have follow-up questions.

File: src/wasm-tree-sitter-language-mode.js (hunk 5 above)
Comment (savetheclocktower) [reply src/wasm-tree-sitter-language-mode.js:3303]: I think I've already caught this one and it'll be addressed in next month's PR. :-)

File: packages/symbol-provider-tree-sitter/lib/tree-sitter-provider.js (hunk 6 above)
Comment (savetheclocktower) [reply packages/symbol-provider-tree-sitter/lib/tree-sitter-provider.js:6]: This is me being _incredibly_ paranoid, since we'd only fall back to the right side of that `??` expression if someone extracted the newer version of this package and added it to an older version of Pulsar.
