### PR TITLE
[about] Link release notes to `CHANGELOG.md` instead of tagged release of Pulsar

### LINKED ISSUE #283: "About" release notes link to non-existent changelog/release notes on github
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Open the about page (Help > About) or `Application: About` on a non-tagged release (tested on latest Cirrus binary - presumably happens in dev but about package seems to be broken in dev entirely).

Click "Release notes" next to the version number, it will open a browser to a github tagged release that doesn't exist because it is using the timestamp as part of it.

`https://github.com/pulsar-edit/pulsar/releases/tag/v1.100.2022122803`

Seems to be from:

https://github.com/pulsar-edit/pulsar/blob/4e20a34082e730a6148821a50dc3561f6ea3382d/packages/about/lib/update-manager.js#L135-L137

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 21

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

From a Cirrus binary (not a tagged GH release):

- Help > About (or `Application: About`)
- Click "Release notes"
image
- Link opens to page that does not exist because we don't create tags for every single CI binary
- https://github.com/pulsar-edit/pulsar/releases/tag/v1.100.2022122803

### Additional Information:

Atom seemingly had a number of ways of dealing with this due to its release channels such as ignoring entirely on dev etc.

A number of options we could look at:

- We find a way of seeing if this is a dev or CI binary and disable this entirely
- We leave it as it is, CI binaries wouldn't be expected to have this kind of feature
- We cut the version off before the datestamp so we always pull release notes for the actual main version. (v1.100.?)
- We remove the browser based version entirely and rely on internal pulsar changelog only

### PR DESCRIPTION
**Pull request by confused-Techie**
Currently the release notes returned by the `about` package attempt to link to a tagged release of Pulsar. This works fine for the regular release of Pulsar, but will link to a non-existent page when used in a Rolling Release.

While there was talks of other methods of fixing this issue, especially now that we do have the `pulsar-rolling-release` repo (although that repo has no release notes on each published version).

The simplest answer was to return the link to Pulsar's `CHANGELOG.md`. The biggest benefit of using this and using an anchor tag to link to a specific version, means it will work on all regular releases, and in the event someone on a rolling release uses this link, the anchor tag will not resolve, and instead will link to the top of the page, thus showing the user the `[Unreleased]` notes, which should mostly be applicable to their rolling release details.

Additionally on this PR, since I had the chance, I removed the logic of finding a `nightly` release repo, since we do not use that logic at all. And since we are now linking via an anchor tag, I've removed the logic of appending a `v` to the version, and instead we now remove it if present, since this character is not present in our changelog notes.

Resolves #283

### CODE REVIEW

File: packages/about/lib/update-manager.js [hunk 1]
```diff
@@ -14,13 +14,11 @@ let UpdateManager = class UpdateManager {
       return 'https://pulsar-edit.dev/download.html';
```
Comment (DeeDeeG) [inline packages/about/lib/update-manager.js:14]: We could probably link to the `CHANGELOG.md` on GitHub when running `-dev` versions of Pulsar as well?

(Basically consolidate all the cases to link to --> `CHANGELOG.md` on GitHub.)

---

<details><summary><b>Historical Context</b> (click to expand):</summary>

This used to be a link to a page at atom.io that basically re-hosted the GitHub Releases notes of every Atom release, for whatever reason. Seems kinda redundant, but it had its own styled CSS, some visual flair points, I suppose...

- Old code: https://github.com/pulsar-edit/pulsar/blame/f15eefb147a901447127a87b27fd18595f2ebe7d/packages/about/lib/update-manager.js#L126-L129
- Old code linked to this page (archived version from original): https://web.archive.org/web/20221210014824/https://atom.io/releases

<details><summary>Huge, extremely very long screenshot (click to open, at your own risk/peril):</summary>

Atom.io Releases Page (Archived from original) -- really long screenshot by the way

</details>

</details>

File: packages/about/spec/update-manager-spec.js
Comment (DeeDeeG) [inline packages/about/spec/update-manager-spec.js:1]: Test changes look reasonable to me! 👍 on this, looks good given the changes in the actual code being tested.

**Review by DeeDeeG — APPROVED** [review]
Assuming this works in testing, then I approve as-is, or with one suggested change to even further consolidate the different version handling stuff a bit.

File: packages/about/lib/update-manager.js (hunk 1 above)
Comment (confused-Techie) [reply packages/about/lib/update-manager.js:14]: Ya know @DeeDeeG this is a fantastic suggestion! Especially considering we don't list any release notes on the website, it makes very little sense now at all. I'll add that in.

(And boy you weren't lying about the length of your screen shot lol)

**Comment by confused-Techie** [comment]
@DeeDeeG added your suggestion here, thanks again for the review!

File: packages/about/spec/update-manager-spec.js
Comment (DeeDeeG) [inline packages/about/spec/update-manager-spec.js:1]: Can we retain a test for `-dev` versions, with whatever the output is there, just to test the function still handles those without asploding?

Maybe with a comment that the anchor is "_expected_ to look weird," if there is one, "since it doesn't hurt anything to have an #anchor that doesn't lead to a real anchor on the page"? Or something like that?

Comment (DeeDeeG) [reply packages/about/spec/update-manager-spec.js:1]: For good measure, it'd be neat to test a Rolling version, too, for example `1.108.2023090322`? (Grabbed the latest version string from https://github.com/pulsar-edit/pulsar-rolling-releases/releases)

But I think we get the idea with testing Regular + `-dev` versions, so it's not strictly necessary.

Comment (confused-Techie) [reply packages/about/spec/update-manager-spec.js:1]: Yeah no worries, I'll happily add those in

Comment (confused-Techie) [reply packages/about/spec/update-manager-spec.js:1]: @DeeDeeG And done, a few extra tests for peace of mind

**Comment by confused-Techie** [comment]
Appreciate the approval @DeeDeeG, and with all tests passing lets get this one merged

**Comment by wesinator** [comment]
The link is not correct in pulsar 1.129.0 on macOS downloaded from https://pulsar-edit.dev/download.html - it loads the entire minor+patch date version number in the anchor.

File: packages/about/spec/update-manager-spec.js [hunk 2]
```diff
@@ -8,27 +8,20 @@ describe('UpdateManager', () => {
...
-      ).toContain('pulsar-edit.dev/download');
+    it('returns the page for the release even when a dev version', () => {
+      expect(updateManager.getReleaseNotesURLForVersion('1.100.0-dev')).toContain(
+        'pulsar-edit/pulsar/blob/master/CHANGELOG.md#11000-dev'
+      );
     });
-
     it('returns the page for the release when not a dev version', () => {
+      expect(updateManager.getReleaseNotesURLForVersion('1.108.2023090322')).toContain(
+        'pulsar-edit/pulsar/blob/master/CHANGELOG.md#11082023090322'
```
Comment (wesinator) [inline packages/about/spec/update-manager-spec.js:18]: isn't this the dev version? ^

Comment (savetheclocktower) [reply packages/about/spec/update-manager-spec.js:18]: Yeah, I think the idea is that it brings you to the `CHANGELOG.md` from `master`, but the hash in the URL jumps you to the applicable section for your version. And in cases like this where the version is nonexistent, it simply doesn't jump anywhere, so you are near the “[Unreleased]” section at the top.

The only problem with this is that this section is empty 99% of the time, because remembering to update `CHANGELOG.md` with each individual pull request is doomed to failure. I'm the most prolific contributor to this repo lately and I never, ever, ever remember to do it, so odds are good that most contributors won't remember to do it either.

But since we're talking about rolling releases, the only other option is to link to the literal list of commits on master, which may or may not be better than the status quo.

Comment (wesinator) [reply packages/about/spec/update-manager-spec.js:18]: that makes sense to me, but I think the test spec could be reworked to be more accurate then? This test for a "dev" version with a long release number is under the spec for "not a dev version".
I don't know if there are any "dev" versions still that use a '-dev' label?

Comment (wesinator) [reply packages/about/spec/update-manager-spec.js:18]: #1329

Comment (DeeDeeG) [reply packages/about/spec/update-manager-spec.js:18]: I'm not sure if you can see the resolved comments above, at the top of the file, but I asked for this separate check to remain, even though literal `-dev` in the version string is an original Atom thing and not something we do anymore in Pulsar project.

The phrasing could be clearer, but `-dev` and our date-based Rolling version strings with lots of digits were intended to be seen as separate things in these tests -- Rolling is not being called a "dev" version, since we don't precisely use that "dev" term for any of our actual versions or releases, to split some hairs.

Here is what I asked for some almost two years ago:

> Sorry to be a tad annoying, but:
> 
> Can we retain a test for `-dev` versions, with whatever the output is there, just to test the function still handles those without asploding?
> 
> Maybe with a comment that the anchor is "_expected_ to look weird," if there is one, "since it doesn't hurt anything (to have an #anchor that doesn't lead to a real anchor on the page)"? Or something like that?

and

> For good measure, it'd be neat to test a Rolling version, too, for example 1.108.2023090322? (Grabbed the latest version string from https://github.com/pulsar-edit/pulsar-rolling-releases/releases)

And this PR's author did so in response to my review feedback.

Perhaps the phrasing in the tests could clarify the potential for confusion between "dev" and "Rolling".

Comment (wesinator) [reply packages/about/spec/update-manager-spec.js:18]: updated #1329
