### PR TITLE
[autocomplete-css] Sort `completions.json`

### LINKED ISSUE #541: [autocomplete-css] Suggestions are ordered strangely
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When starting to type something like "wid" in a CSS file, I get recommendations such as "windows" before something like "width". 

Also when typing "padd" or "marg" I get suggestions for "padding-top" before "padding".
This used to not be the case when I first installed Pulsar (not sure the version) but recently its regressed. 

Any suggestions would be great. 

### Pulsar version

1.105.0

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

N/A

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

N/A

### Additional Information:

_No response_

### PR DESCRIPTION
**Pull request by confused-Techie**
In this PR I've added two new features to the script that generates the `completions.json`.

  * `lengthSort()`: This runs right after the file has been fully generated. Sorting every property key by it's length, moving the shortest values to the top of the list.
  * `popularSort()`: This runs next, sorting all keys based on popularity, according to [Chrome Platform CSS usage metrics](https://chromestatus.com/metrics/css/popularity).

The `completions.json` file doesn't seem to have any other changes other than now being sorted.

~~Additionally, you can see in my first commit here I simply moved all relevant files into an `update` folder, so for the sake of reviewing I wouldn't suggest looking much at that first commit, but it contained zero other changes.~~ (EDIT: nevermind, GitHub recognizes the file was moved, so the diff isn't difficult to read. Ignore that)

Also, I've gone ahead and removed the no longer used `request` dependency, and replaced it with `superagent` which we do now need. I've already done the same exact thing over on #474. This was just now relevant to what I was doing, as I needed a way to download the Chrome usage metrics.

---

Resolves #541

### CODE REVIEW

File: packages/autocomplete-css/update/update.js [hunk 1]
```diff
@@ -103,8 +104,13 @@ async function update(params) {
     pseudoSelectors: pseudoSelectors
   };
 
+  // Now lets sort the properties according to length
+  completions.properties = lengthSort(completions.properties);
+  // Then lets sort properties by popularity
+  completions.properties = await popularSort(completions.properties);
```
Comment (savetheclocktower) [inline packages/autocomplete-css/update/update.js:110]: Why not just sort by popularity? What practical difference does it make to sort by length first?

Comment (confused-Techie) [reply packages/autocomplete-css/update/update.js:110]: This goes with what you were suggesting previously, that it would be better to always sort by length, so that shorter results appear before longer ones. Which I totally agree with, and if it were up to me would be the only sorting we were doing.

But beyond that, it had to be done first, so that we still prioritize popularity over it. Since now everything that doesn't exist in Chrome's popularity metric is sorted by length

Comment (savetheclocktower) [reply packages/autocomplete-css/update/update.js:110]: Oh, I didn't look closely enough. This code only runs when `completions.json` is updated. I was worried about performance for users, but that's not a concern here.

Comment (savetheclocktower) [inline packages/autocomplete-css/update/update.js:110]: Here's a magic trick that makes the comments superfluous ;-)

```suggestion
  completions.properties = sortByLength(completions.properties);
  completions.properties = await sortByPopularity(completions.properties);
```

Comment (confused-Techie) [reply packages/autocomplete-css/update/update.js:110]: Fantastic point, lemme make that change real quick

Comment (confused-Techie) [reply packages/autocomplete-css/update/update.js:110]: Yeah this will only effect our running time, and even though while I'm pretty sure this is in the quadratic big o notation territory, it only takes a second to run, plus I wanted to make sure we still sorted for items that aren't listed in the metrics, since I highly doubt everything's there

**Review by mauricioszabo — APPROVED** [review]
Sounds solid, an easy :+1: :)
